import React from 'react'
import { Shield } from 'lucide-react'

interface TwoFAModalProps {
  closePopUp: () => void
}

export default function TwoFAModal({ closePopUp }: TwoFAModalProps) {
  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-md flex items-center justify-center z-50 animate-in fade-in-0 zoom-in-95 duration-200">
      {/* Modal */}
      <div className="relative flex items-center justify-center h-full">
        <div className="bg-white dark:bg-black rounded-lg p-6 max-w-lg mx-4 shadow-xl border border-gray-300 dark:border-gray-700">
          {/* Title */}
          <h2 className="text-black dark:text-white text-xl font-bold mb-4 flex items-center gap-2">
            <Shield className="w-6 h-6 text-blue-600" />
            What is Two-Factor Authentication?
          </h2>

          {/* Description */}
          <p className="text-gray-700 dark:text-gray-300 text-sm mb-6 leading-relaxed">
            Two-Factor Authentication (2FA) adds an extra layer of security to your account. In addition to your password, you'll need a second form of verification, such as a code sent to your phone or generated by an app. This helps protect your account from unauthorized access, even if someone knows your password.
          </p>

          {/* Buttons */}
          <div className="flex justify-end">
            <button
              onClick={closePopUp}
              className="cursor-pointer bg-blue-600 hover:bg-blue-700 text-white rounded-md w-full py-2 text-sm font-medium transition-colors"
            >
              Got it
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
