version: "3.9"

services:
  app:
    build: .
    container_name: briezl_app

    ports:
      - "3000:3000"

    env_file:
      - .env.local

    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s